# Generated by Django 5.0.6 on 2024-09-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='answer',
            new_name='response',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Text Box'), (2, 'Single Choice'), (3, 'Multiple Choice')], verbose_name='Question Type'),
        ),
    ]
