# Generated by Django 5.0.6 on 2024-09-29 08:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_alter_option_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.IntegerField(choices=[(1, 'Text Box'), (2, 'Single Choice'), (3, 'Multiple Choice'), (3, 'Absolute Location')], verbose_name='Question Type'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey_response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaire.surveyresponse'),
        ),
    ]
