# Generated by Django 5.0.6 on 2024-09-29 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_surveyresponse_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaire.surveyresponse'),
        ),
    ]
