# Generated by Django 5.0.6 on 2024-09-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_alter_response_survey_response'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SurveyResponse',
            new_name='Survey',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='survey_response',
            new_name='survey',
        ),
    ]
