# Generated by Django 5.1.1 on 2024-09-11 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_is_staff_remove_user_is_super_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='added_by',
        ),
    ]
